default_platform(:ios)

platform :ios do
  desc "Build an iOS app for release"
  lane :build do
    build_app(scheme: "Runner")
  end

  desc "Build and upload to TestFlight and App Store (requires setup)"
  lane :release do
    build_app(scheme: "Runner")
    upload_to_testflight
    upload_to_app_store
  end
end
